package uk.gov.hmcts.reform.divorce.orchestration.domain.model.email;

public enum EmailTemplateNames {
    AOS_RECEIVED_NO_ADMIT_ADULTERY,
    AOS_RECEIVED_NO_ADMIT_ADULTERY_CORESP_NOT_REPLIED,
    AOS_RECEIVED_NO_CONSENT_2_YEARS,
    APPLIC_SUBMISSION,
    DN_SUBMISSION,
    GENERIC_UPDATE,
    RESPONDENT_SUBMISSION_CONSENT,
    RESPONDENT_SUBMISSION_CONSENT_CORESP_NOT_REPLIED,
    RESPONDENT_DEFENDED_AOS_SUBMISSION_NOTIFICATION,
    RESPONDENT_UNDEFENDED_AOS_SUBMISSION_NOTIFICATION,
    CO_RESPONDENT_DEFENDED_AOS_SUBMISSION_NOTIFICATION,
    CO_RESPONDENT_UNDEFENDED_AOS_SUBMISSION_NOTIFICATION,
    SAVE_DRAFT,
    PETITIONER_CLARIFICATION_REQUEST_EMAIL_NOTIFICATION,
    PETITIONER_CERTIFICATE_OF_ENTITLEMENT_NOTIFICATION
}
