package uk.gov.hmcts.reform.divorce.orchestration.domain.model.email;

public enum EmailTemplateNames {
    APPLIC_SUBMISSION,
    DN_SUBMISSION,
    GENERIC_UPDATE,
    RESPONDENT_SUBMISSION_CONSENT,
    RESPONDENT_DEFENDED_AOS_SUBMISSION_NOTIFICATION,
    RESPONDENT_UNDEFENDED_AOS_SUBMISSION_NOTIFICATION,
    CO_RESPONDENT_DEFENDED_AOS_SUBMISSION_NOTIFICATION,
    CO_RESPONDENT_UNDEFENDED_AOS_SUBMISSION_NOTIFICATION,
    SAVE_DRAFT
}
