---
version: '2.1' 

services: 
  claim-store-database:
    build:
      context: docker/database
    image: hmcts/div-store-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DIV_STORE_DB_USERNAME
      - DIV_STORE_DB_PASSWORD
    ports:
      - 5430:5432
    volumes:
      - div-store-database-data:/var/lib/postgresql/data

volumes:
  div-store-database-data:
